# Generated by Django 5.1.4 on 2024-12-30 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import suziai_human_annotation.core.models.files


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sample",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "image",
                    models.ImageField(
                        upload_to=suziai_human_annotation.core.models.files.filename_generator("samples/")
                    ),
                ),
                ("real_name", models.CharField(max_length=128, unique=True)),
                (
                    "real_pitch",
                    models.CharField(
                        choices=[
                            ("NONE", "none"),
                            ("HE", "he"),
                            ("SI", "si"),
                            ("YI", "yi"),
                            ("SHANG", "shang"),
                            ("GOU", "gou"),
                            ("CHE", "che"),
                            ("GONG", "gong"),
                            ("FAN", "fan"),
                            ("LIU", "liu"),
                            ("WU", "wu"),
                            ("GAO_WU", "gao wu"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "real_secondary",
                    models.CharField(
                        choices=[
                            ("NONE", "none"),
                            ("DA_DUN", "da dun"),
                            ("XIAO_ZHU", "xiao zhu"),
                            ("DING_ZHU", "ding zhu"),
                            ("DA_ZHU", "da zhu"),
                            ("ZHE", "zhe"),
                            ("YE", "ye"),
                        ],
                        max_length=16,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Annotation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "pitch",
                    models.CharField(
                        choices=[
                            ("NONE", "none"),
                            ("HE", "he"),
                            ("SI", "si"),
                            ("YI", "yi"),
                            ("SHANG", "shang"),
                            ("GOU", "gou"),
                            ("CHE", "che"),
                            ("GONG", "gong"),
                            ("FAN", "fan"),
                            ("LIU", "liu"),
                            ("WU", "wu"),
                            ("GAO_WU", "gao wu"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "secondary",
                    models.CharField(
                        choices=[
                            ("NONE", "none"),
                            ("DA_DUN", "da dun"),
                            ("XIAO_ZHU", "xiao zhu"),
                            ("DING_ZHU", "ding zhu"),
                            ("DA_ZHU", "da zhu"),
                            ("ZHE", "zhe"),
                            ("YE", "ye"),
                        ],
                        max_length=16,
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ("sample", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.sample")),
            ],
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "annotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="actions", to="core.annotation"
                    ),
                ),
            ],
        ),
    ]
