# Generated by Django 5.1.4 on 2024-12-30 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_annotation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="sample",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="annotations", to="core.sample"
            ),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="annotations", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
