# Generated by Django 5.1.4 on 2024-12-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="secondary",
            field=models.CharField(
                choices=[
                    ("NONE", "none"),
                    ("DA_DUN", "da dun"),
                    ("XIAO_ZHU", "xiao zhu"),
                    ("DING_ZHU", "ding zhu"),
                    ("DA_ZHU", "da zhu"),
                    ("ZHE", "zhe"),
                    ("YE", "ye"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="real_secondary",
            field=models.CharField(
                choices=[
                    ("NONE", "none"),
                    ("DA_DUN", "da dun"),
                    ("XIAO_ZHU", "xiao zhu"),
                    ("DING_ZHU", "ding zhu"),
                    ("DA_ZHU", "da zhu"),
                    ("ZHE", "zhe"),
                    ("YE", "ye"),
                ],
                max_length=16,
            ),
        ),
    ]
