[tool.ruff]
line-length = 120
respect-gitignore = true
extend-exclude = [".venv", "__pycache__"]
show-fixes = true

[tool.ruff.format]
quote-style = "double"

[tool.ruff.lint]
select = ["A", "B", "C", "E", "F", "I", "W", "T20", "LOG", "UP", "RUF010", "RUF019"]
ignore = ["E203", "E266", "E501", "F403", "F405"]

[tool.ruff.lint.isort]
known-first-party = ["suziai_human_annotation"]
section-order = [
    "future",
    "standard-library",
    "django",
    "djangorestframework",
    "third-party",
    "first-party",
    "local-folder",
]

[tool.ruff.lint.isort.sections]
"django" = ["django"]
"djangorestframework" = ["rest_framework"]

[tool.ruff.lint.per-file-ignores]
"apps.py" = ["F401"]
