FROM python:3.12-slim-bookworm

# Set non-interactive mode for apt-get
ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1

# Install required packages
RUN apt-get update \
    && apt-get install -y \
        gosu \
        dos2unix \
        sqlite3 \
    && rm -rf /var/lib/apt/lists/*

# Install Python requirements
COPY ./requirements /requirements
RUN pip install --no-cache-dir -r /requirements/production.txt

# Install application
COPY ./src /app
WORKDIR /app
