name: Build and publish container images

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      IMAGE_PREFIX: ghcr.io/${{ github.repository }}
      IMAGE_VERSION: ${{ github.event.release.tag_name || 'next' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build images
        run: |
          IMAGE_PREFIX=${IMAGE_PREFIX@L} docker compose -f docker-compose-prod.yml build

      - name: Push images
        run: |
          IMAGE_PREFIX=${IMAGE_PREFIX@L} docker compose -f docker-compose-prod.yml push
